### ISSUE TITLE
Equal/allclose and friends should not hide ValueError

### ISSUE THREAD

**Issue by cbenmahm** [lab-cosmo/equistore#175]
comparing two empty tensor maps (same keys but the blocks are an empty list) using `equistore.equal` gives a `False`

**Comment by Luthaf** [comment]
There are a couple of operations impacted: equal, allclose (as well as the `_block` version), maybe others.  The way these function work is by calling the `_raise` version, and catching all ValueError, returning False if an exception was raised. Unfortunately, this hides exceptions coming from elsewhere, such as the one initially discussed here.

A simple fix would be to use a new exception type for the `_raise` version of the functions, for example `class NotEqual(Exception): pass` and raise/catch this exception instead of the generic `ValueError` one.
