### ISSUE TITLE
operations.join fails with non-empty components tensor blocks

### ISSUE THREAD

**Issue by bananenpampe** [lab-cosmo/equistore#195]
Joining two TensorMaps fails when the Tensorblocks contain non-empty components

Join two tensor maps with empty components
```python
import equistore
import equistore.operations as eqst
import numpy as np

s_labels = equistore.Labels(names=["idx"],values=np.arange(1).reshape(-1,1))
components = [] #equistore.Labels(["sym"], np.asarray([[0]], dtype=np.int32))]
properties = equistore.Labels(["eV"], np.asarray([[0]], dtype=np.int32))

tensor_map_a = equistore.TensorMap(keys=equistore.Labels(["frame_a"], np.asarray([(0,)], np.int32)),\
                                   blocks=[equistore.TensorBlock(values=np.zeros(1).reshape(1,1),\
                                   samples=s_labels,components=components,properties=properties)])

tensor_map_b = equistore.TensorMap(keys=equistore.Labels(["frame_a"], np.asarray([(0,)], np.int32)),\
                                   blocks=[equistore.TensorBlock(values=np.zeros(1).reshape(1,1),\
                                                                 
                                   samples=s_labels,components=components,properties=properties)])

eqst.join([tensor_map_a,tensor_map_a],axis="properties")

# ->
# TensorMap with 1 blocks
#  keys: ['frame_a']
#          0
#

```

Join two tensor maps with non-empty components

```python
s_labels = equistore.Labels(names=["idx"],values=np.arange(1).reshape(-1,1))
components = [equistore.Labels(["sym"], np.asarray([[0]], dtype=np.int32))]
properties = equistore.Labels(["eV"], np.asarray([[0]], dtype=np.int32))

tensor_map_a = equistore.TensorMap(keys=equistore.Labels(["frame_a"], np.asarray([(0,)], np.int32)),\
                                   blocks=[equistore.TensorBlock(values=np.zeros(1).reshape(1,1,1),\
                                   samples=s_labels,components=components,properties=properties)])

tensor_map_b = equistore.TensorMap(keys=equistore.Labels(["frame_a"], np.asarray([(0,)], np.int32)),\
                                   blocks=[equistore.TensorBlock(values=np.zeros(1).reshape(1,1,1),\
                                   samples=s_labels,components=components,properties=properties)])

#
eqst.join([tensor_map_a,tensor_map_a],axis="properties")

#-> EquistoreError: invalid parameter: data and labels don't match: 
# the array shape along axis 1 is 2 but we have 1 entries for the corresponding component
```

I use python 3.10.4 and equistore commit 16ff8ea

**Comment by jwa7** [comment]
I have also experienced a bug here. I think the problem is that the private function `_join_blocks_along_properties()` dispatches to `hstack`, when it should in fact use a `dstack`. 

`hstack` should be used for joining along the components axis, and `dstack` should be used for joining along properties. In our draft PR #197 , we have updated `_dispatch.py` to include a `dstack` operation, which we use in our `transpose` function to join values along the properties dimension.

**Comment by PicoCentauri** [comment]
> `hstack` should be used for joining along the components axis, 

do you mean `samples` axis here?

> `dstack` should be used for joining along properties.

Are you sure that `dstack` is doing the job? I think we need something which is joining along the last axis and not the the third as it is the case for dstack.

**Comment by jwa7** [comment]
Hmm yes I see your point, `dstack` might work in some cases but not be generally true. Perhaps we should use a `_dispatch.stack` function (based on `numpy.stack` or `torch.stack`) for all our applications (i.e. `equistore.join`, `equistore.tranpose`, etc) and specify the axis explicitly so that we avoid bugs and maintain generality.

https://numpy.org/doc/stable/reference/generated/numpy.stack.html#numpy.stack
https://pytorch.org/docs/stable/generated/torch.stack.html
