### ISSUE TITLE
copy function for tensor map

### ISSUE THREAD

**Issue by agoscinski** [lab-cosmo/equistore#98]
I think that would be just a simple helper function, because the copy function for tensor block already exists. So one needs to only create one loop. I am just not sure where this should be implemented. Python API or in the core?

**Comment by Luthaf** [comment]
That's fair, let's do this in the core + C/C++/Python API. This might need to wait for #85 to be merged first.

I would not use this for the copy constructor in C++ though since it is way to easy to call it by default (instead we can have a clone function on the TensorMap class, like we already do for blocks: https://github.com/lab-cosmo/equistore/blob/e65cd07d2f0d5aefa41a7b2beade835b9b1dc03b/include/equistore.hpp#L1204)
