### ISSUE TITLE
User layer for TensorBlock index operations through bracket operator

### ISSUE THREAD

**Issue by agoscinski** [lab-cosmo/equistore#99]
I wonder if could have these advance indexing operations available with the bracket operator like in numpy `[ ]` to have a similar feel of numpy arrays. I think it is easy to think about the tensor block (TB) as a 3D array and then do very similar things like slicing and indexing. Under the hood the equistore operations are still used. For some index operations I think it becomes not so trivial to do, but for slicing this should be easy to do.

**Comment by Luthaf** [comment]
Could you write some example API? I'm not sure I see how one would use this.

**Comment by agoscinski** [comment]
Basically the same slicing operations as in numpy (':5', '::2', '-1', [1,3,5,9]). this is one only allowed when components are empty, then operation is applied on the two dimensions of samples and properties. Then it could be also applied on the gradients where it the components are not touched by the slicing operation. One could probably also add support for components, but this seems more complicated for now.

**Comment by agoscinski** [comment]
Okay I just learned that samples in Gradients and TensorBlock do not need to agree with each other. So the slicing would need to check that the Labels are the same, otherwise it does not work. On one hand this is a limited use case, but on the other hand it gives you back that easy numpy feeling in cases when you are just dealing with simple blocks or maps.

**Comment by Luthaf** [comment]
I would prefer not to add operations that only work in some cases (i.e. "only if you don't have components" or "only if all gradients are exactly the same"), because they introduce arbitrary road blocks when trying to do more complex things ("why does this code fail for LODE, it worked with SOAP?"). This is especially true for code that goes inside this repository or equisolve, where we can not assume much about the data that is being stored.

If users prefer working with a single numpy array (and the data can be transformed into a single array, i.e. there are no gradients and a single block), then equistore makes it very easy to get the data out and just use an array.

**Comment by agoscinski** [comment]
I see your point, and will close the issue. I still feel there is a need to simplify the slice operation in some way, even though the suggested way in this issue is probably not the right way. But I think there are other issues about equistore which should get the attention for the moment
